TOP = tb_id_stage

RTL = ../rtl/id_stage.v \
      ../rtl/regfile.v \
      ../rtl/imm_gen.v \
      ../rtl/decode_ctrl.v

TB  = ../tb/tb_id_stage.sv

all:
	verilator -Wall --trace --Wno-fatal \
	  --cc $(RTL) $(TB) \
	  --top-module $(TOP) \
	  --exe sim_main_id.cpp
	make -C obj_dir -f V$(TOP).mk
	./obj_dir/V$(TOP)

clean:
	rm -rf obj_dir dump.vcd
